/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "TRPC": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "TURSO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
