/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "D1_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "accountId": string
      "id": string
      "type": "sst.sst.Linkable"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "D1": cloudflare.D1Database
    "TRPC": cloudflare.Service
  }
}
