/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "TURSO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "TRPC": cloudflare.Service
  }
}
